### ISSUE TITLE
add badges to index

### ISSUE THREAD

**Issue by sgbaird** [sgbaird/honegumi#17]
stars, follow, discussion, etc.

**Comment by hiirrxnn** [comment]
Can i work on this?

**Comment by sgbaird** [comment]
For sure! Shields.io is usually a good one to use

**Comment by sgbaird** [comment]
@hiirrxnn
Maybe just the GitHub specific ones from https://github.com/sparks-baird/xtal2png/blob/main/docs/index.md?
Note:
```
<script async defer src="https://buttons.github.io/buttons.js"></script>
```
needs to be added at the end of the file for this to work.

Open to other suggestions. Maybe tests and docs passing badges, too?

**Comment by sgbaird** [comment]
@hiirrxnn as an aside, I'm also curious to get your thoughts on the new options I'm implementing in the dev branch: https://honegumi.readthedocs.io/en/dev/.
